suppressPackageStartupMessages({
  library(argparse)
  library(dplyr)
  library(data.table)
})

options(scipen=999)

# Calculate bp distance between two consecutive DNA motif
dist_f <- function(data) {
    data  %>%
    group_by(V1) %>%
    mutate(distance = abs(V2 - lag(V3))) %>% # Create new column for bp-distance values
    ungroup()
}

# Define a function to get color based on distance/model
# 0 means 0 monomer between two monomers with the DNA motif
# 1 means 1 monomer between two monomers with the DNA motif
# 2 means 2 monomer between two monomers with the DNA motif
get_color_from_model <- function(model) {
  if (is.na(model)) {
    return("0,0,0")  # Return black if the distance is NA, keeping the NA for IGV visualization of the first CENP-B box of the chromosome
  }
  color_row <- distance_f[distance_f$distance == model, "color"]
  if (length(color_row) > 0) {
    return(as.character(color_row))
  } else {
    return("0,0,0")  # Return black for distances not found in the color file / <1% represented
  }
}

# Calculating the relationship with monomers
# 171 because of 1 nt between each monomer and monomer's length (169-170bp)
ratio <- function(data){
  data %>% mutate(ratio = abs((distance / 171) - 1)) %>% ungroup()
}

# Round each value to the nearest whole number ensuring the result has no decimal places
counting <- function(data){
  data$model <- round(data$ratio, digits = 0)
  return(data)
}

parser <- ArgumentParser(description = "Model2 generates a BED file highlighting the conservation of the motif organization with respect to alpha-satellite monomers")
parser$add_argument("-i", "--input", required = TRUE, help = "DNA motif annotation file, generated by fuzznuc module", type = "character", metavar = "FILE")
parser$add_argument("-d", "--distance", required = TRUE, help = "Tab-separated file where the distance column contains the number of monomers between two monomers with the DNA motif and the color column reports the associated color", type = "character", metavar = "FILE")
parser$add_argument("-o", "--output_file", help = "Name of the output file [default model2.bed]", type = "character", default = "model2.bed", metavar = "FILE")

# Parse args
args <- parser$parse_args()

# Check if both parameters are provided
if (is.null(args$input) || is.null(args$distance)) {
  cat("HELP: Both '--input' (DNA motif annotation file) and '--distance' (distance/model and color file) are required!\n")
  quit(status = 1) # Exit the script with an error status
} else {
  cat("Reading input files...\n")
  data_f <- fread(args$input)
  distance_f <- fread(args$distance)
  output_file <- (args$output_file)
}

distance_f <- as.data.frame(distance_f)
data_f <- data_f[order(V1, V2)]

# Creating list of dataframe by chromosome
data_f <- split(data_f, data_f$V1)

cat("Calculating bp-distances...\n")
data_fd <- lapply(data_f, dist_f) # bp-distance
data_fd <- lapply(data_fd,na.omit) #to remove all the NA distance values (NA values belong to the first CENP-B box of the chromosome)

#cat("Subsetting bp-distances...\n")
#data_fd <- lapply(data_fd, subset_by_distance)

cat("Calculating models based on distances...\n")
data_fd <- lapply(data_fd,ratio)
data_fd <- lapply(data_fd, counting)

cat("Assigning colors to model...\n")
for (i in seq_along(data_fd)) {
  # Add a new column 'color' to each table
  data_fd[[i]]$color <- sapply(data_fd[[i]]$model, get_color_from_model)
}

data_fd <- lapply(data_fd, function(data_fd) {
  data_fd$color <- as.character(data_fd$color)  # Convert to character (adjust as needed)
  return(data_fd)
})


data_fd <- bind_rows(data_fd)

# Giving a name to the distance values and model
data_fd$distance <- paste0("D", data_fd$distance)
data_fd$model <- paste0("M", data_fd$model)

data_fd <- data_fd[, c(1,2,3,7,4,1,2,3,8)]

#output_file <- file.path(dirname(args$input), "model2.bed")
write.table(data_fd, output_file, sep="\t", col.names = F, row.names = F, quote = F)